export default {
  USER_INFO_RECEIVED: 'USER_INFO_RECEIVED',
  SELECTED_USER_ACCOUNT: 'SELECTED_USER_ACCOUNT',
  RESET_STATE: 'RESET_STATE',
  DASHBOARD: 'DASHBOARD',
  GET_PROFILE_STATUS: 'GET_PROFILE_STATUS',
  LOADING: 'LOADING',
  TOAST: 'TOAST',
};
